export const DISPLAY_ALERT = 'DISPLAY_ALERT'
export const CLEAR_ALERT   = 'CLEAR_ALERT'

export const REGISTER_USER_BEGIN   = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR   = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN   = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR   = 'LOGIN_USER_ERROR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_TASK_BEGIN = 'CREATE_TASK_BEGIN'
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR'

export const GET_TASKS_BEGIN = 'GET_TASKS_BEGIN'
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS'
export const GET_TASKS_ERROR = 'GET_TASKS_ERROR'

export const SET_UPDATE_TASK_BEGIN = 'SET_UPDATE_TASK_BEGIN'

export const UPDATE_TASK_BEGIN = 'UPDATE_TASK_BEGIN'
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'
export const UPDATE_TASK_ERROR = 'UPDATE_TASK_ERROR'

export const DELETE_TASK_BEGIN = 'DELETE_TASK_BEGIN'
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR'